# PostgreSQL
#
# Install the PostgreSQL driver:
#   gem 'pg'
#   # On macOS with Homebrew
#   gem 'pg', '~> 1.1', '>= 1.1.4'
#   # On macOS with MacPorts
#   gem 'pg', '~> 0.18.2'
#   # On Windows
#   gem 'pg', '~> 1.1'
#
# Ensure the PostgreSQL gem is defined in your Gemfile
#   gem 'pg'
#
# On macOS, for Postgres.app <https://postgresapp.com/>, you can use this instead:
#   gem 'pg', '~> 1.1', '>= 1.1.4', require: 'pg_ext'
#


default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: myapp
  password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
  host: db

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: myapp_production
